gentoo/gentoo-rust

dev-lang/rust/files/rust-0.13.0-no-ldconfig.patch
dev-lang/rust/rust-9999-r3.ebuild
dev-rust/cargo/files/cargo-9999-no-ldconfig.patch

Fixes https://github.com/Heather/gentoo-rust/issues/44 and https://github.com/Heather/gentoo-rust/issues/41.

dev-lang/rust: fix build and install

---

dev-lang/rust-bin/rust-bin-999.ebuild

Patch isn't working. But option works fine.

Replace no-ldconfig.patch with --disable-ldconfig option.

---

dev-util/racer/racer-9999.ebuild

- Remove extra IUSE line
- Create COMMON_DEPEND variable for common dependencies.
- Move build to src_compile instead of src_configure.
- minor style changes.

dev-util/racer/racer-9999: minor fixes

---

dev-lang/rust/rust-1.0.0_alpha2.ebuild
dev-lang/rust/rust-1.0.0_beta.ebuild
dev-lang/rust/rust-999.ebuild
dev-lang/rust/rust-9999.ebuild

[dev-lang/rust] python2_6 is no longer valid

---

dev-lang/rust/rust-999.ebuild
dev-lang/rust/rust-9999.ebuild

Remove patch fixed upstream

---

dev-lang/rust/rust-1.6.0-r1.ebuild

Drop old patch to fix 1.6 install paths

---

www-apps/geckodriver/geckodriver-0.10.0.ebuild
www-apps/geckodriver/geckodriver-0.11.1.ebuild

www-apps/geckodriver: bump EAPI to 6

---

dev-util/SolidOak/SolidOak-9999.ebuild

dev-util/SolidOak: Fix compilation issues.

---

dev-lang/rust/files/rust-9999-enable-analysis-dev.patch

Fix error after https://github.com/rust-lang/rust/commit/57c989caa1db0b000ff5e9fd2ebb0e6557a3cf30

dev-lang/rust-9999: Fix analysis patch.

---

dev-lang/rust/rust-9999-r1.ebuild

Reverts gentoo/gentoo-rust#288

Revert "Fix #287 and restore git data."

---

dev-lang/rust-bin/rust-bin-999.ebuild

rls component is now called rls-preview
fixes #291

Fix dev-lang/rust-bin-999

---

dev-lang/rust/files/rust-1.20.0-fix-libdir.patch
dev-lang/rust/rust-1.20.0.ebuild

Use some fix from https://github.com/rust-lang/rust/issues/45345
Fixes https://github.com/gentoo/gentoo-rust/issues/287
1.21 and later get error with documentation.

dev-lang/rust-1.20.0: Use custom libdir.

---

dev-lang/rust/rust-1.23.0.ebuild

dev-lang/rust-1.23.0: version bump

dev-lang/rust-1.23.0: version bump

---

eclass/cargo.eclass

add basic support to cargo test via src_test

[eclass/cargo.eclass] add test

---

.travis.yml

Signed-off-by: layman <layman@localhost>

update to portage 2.3.38

---

dev-lang/rust/rust-1.26.0.ebuild

Reverts gentoo/gentoo-rust#349

Revert "Fix stable"

---

dev-lang/rust/rust-9999.ebuild

Made git version more compatible with stable.
Copied from =dev-lang/rust-1.26.1

dev-lang/rust-9999: Enables multilib and LLVM targets.

---

dev-util/wasm-bindgen/wasm-bindgen-9999.ebuild
dev-util/wasm-gc/wasm-gc-9999.ebuild

Add dev-util/[wasm-bindgen](https://github.com/rustwasm/wasm-bindgen)-9999 and dev-util/[wasm-gc](https://github.com/alexcrichton/wasm-gc)-9999 ebuilds

WASM tools

---

virtual/cargo/cargo-9999.ebuild

Add virtual/cargo same as portage's one.

---

app-editors/xi-core/metadata.xml
app-editors/xi-core/xi-core-9999.ebuild
app-editors/xi-gtk/files/xi-gtk-9999-datasubdir.patch
app-editors/xi-gtk/metadata.xml
app-editors/xi-gtk/xi-gtk-9999.ebuild

https://xi-editor.github.io/xi-editor/
https://github.com/eyelash/xi-gtk

Add app-editor/xi-core and app-editor/xi-gtk live ebuilds

---

dev-lang/rust-bin/metadata.xml
dev-lang/rust-bin/rust-bin-9999.ebuild

* rename `tools` useflag to `rls`
* port useflags from stable rust-bin
* move to `EAPI=7`
* move from *.tar.gz to *.tar.xz sources

Update dev-lang/rust-bin-9999 ebuild

---

dev-util/cargo/cargo-9999.ebuild

Fix https://bugs.gentoo.org/669252

Add PowerPC64

---

dev-lang/rust/files/rust-9999-fix-clippy-sysroot.patch
dev-lang/rust/files/rust-9999-fix-codegen-path.patch
dev-lang/rust/rust-9999.ebuild

See https://github.com/rust-lang/rust/pull/57101
and https://github.com/rust-lang/rust-clippy/pull/3257

Fix clippy sysroot patch. Fix codegen search.

---

dev-lang/rust-bin/rust-bin-9999.ebuild

Please merge so I can take this out of my local repository

dev-lang/rust-bin: Functional rustlib targets

---

app-editors/xi-core/xi-core-9999.ebuild

app-editors/xi-core-9999: fix build

---

.travis.yml
dev-lang/rust/rust-1.35.0-r666.ebuild
virtual/rust/rust-1.35.0-r666.ebuild

Fix travis errors

---

dev-lang/rust-bin/metadata.xml
dev-lang/rust-bin/rust-bin-9999.ebuild

I want to do a testrun with updated portage via travis

dev-lang/rust-bin: remove PDEPEND of cargo to make repoman happy

---

dev-rust/qt_generator/qt_generator-9999.ebuild
dev-util/SolidOak/SolidOak-9999.ebuild

fixes for cargo leftovers

---

dev-lang/rust/rust-9999.ebuild

Remove lib fixes after accepting https://github.com/rust-lang/rust/pull/62497

dev-lang/rust-9999: Copy changes from gentoo's ebuild

---

dev-lang/rust-bin/rust-bin-9999.ebuild

this allows nightly testing, needed to tackle these: 
https://github.com/rust-lang/rust/issues/62896
https://github.com/rust-lang/rust/issues/64355

dev-lang/rust-bin-9999: add armv7 and aarch64 support

---

dev-lang/rust-bin/rust-bin-999.ebuild
dev-lang/rust-bin/rust-bin-9999.ebuild

dev-lang/rust-bin: fix failure in name resolution for beta and git

---

dev-lang/rust/files/37c5cb8118b6de04dd5d4e5e43787c8b83339472.patch
dev-lang/rust/rust-999.ebuild
dev-lang/rust/rust-9999.ebuild

also add xz-utils to compile time deps

dev-lang/rust: use tar.xz for stage0 rather than tar.gz
