- dev-rust/rust-bindgen/files/rust-bindgen
- dev-rust/rust-bindgen/metadata.xml
- dev-rust/rust-bindgen/rust-bindgen-9999.ebuild
Rust-bindgen is a highly useful tool, so let's add the ebuild.
> dev-rust/rust-bindgen: new ebuild

- dev-lang/rust/rust-999-r2.ebuild
Nightly sources are now distributed with new file name. Some fixes were
integrated from 9999-r3. Slot conflict in doc folder was solved.
Now it has no conflict with `git` slot but 9999 ebuild also requires a fix for that. It also looks like lldb helper is now changed to gdb helper, so I changed mentions of lldb to gdb.
> fix for nightly builds

- dev-rust/cargo/cargo-9999-r1.ebuild
The ebuild calls `.travis.install.deps.sh` to fetch "those specific rustc" which can build cargo. The problem is that script fetches rust images for both platforms.
Also this ebuild does not require ldconfig patch because it use `CFG_DISABLE_LDCONFIG="true"` when necessary.
If this unnecessary fetches troubles you. I can try to reduce it to one fetch based on how sh script works.
However ebuild works and emerges workable version of cargo. So if it's OK you may pull changes.
> new ebuild for cargo (cargo-9999-r1.ebuild)

- dev-lang/rust/rust-1.0.0_alpha.ebuild
- profiles/package.use.mask
system-llvm is now present as USEflag but masked
as @jauhien suggested in #55 pull request
> rust-1.0.0_alpha: reimplement system-llvm

- dev-lang/rust-bin/rust-bin-999-r1.ebuild
Looks like instead of rust-lldb we now have rust-gdb helper. Fixed
ebuild for this.
This ebuild works. However eselect-rust is not supporting rust-gdb yet.
> rust-bin-999-r1: new ebuild fix lldb error

- app-emacs/rust-mode/rust-mode-9999-r1.ebuild
- app-vim/rust-mode/rust-mode-9999-r1.ebuild
Now plugins for vim and emacs are in separate repositories.
> rust-mode-9999-r1: new repo URLs

- dev-rust/cargo/cargo-9999-r1.ebuild
Aparently ./.travis.install.deps.sh needs BITS variable to be set (at
least for x86). Workaround was added.
Probably fixes #61
> Cargo 32 bit fix

- app-shells/rust-zshcomp/rust-zshcomp-9999-r1.ebuild
Zsh plugin for rust now also has it's own separated repository.
> rust-zshcomp-999-r1: new repo URLs

- dev-lang/rust-bin/rust-bin-999-r1.ebuild
- dev-lang/rust-bin/rust-bin-999.ebuild
- dev-lang/rust/rust-1.0.0_alpha.ebuild
- dev-lang/rust/rust-999-r1.ebuild
- dev-lang/rust/rust-999-r2.ebuild
- dev-lang/rust/rust-9999-r3.ebuild
Gentoo qa policy does not allow use flags to pull in optional runtime
dependencies the package does not link to, so We need to remove the
emacs, vim-syntax and zsh-completion use flags from the dev-lang/rust*
ebuilds [1]. We can, however, output elog messages to the user based on
what they have installed.
[1] https://devmanual.gentoo.org/general-concepts/use-flags/index.html
> Fix qa issue with emacs vim-syntax and zsh-completion use flags

- dev-lang/rust/rust-1.0.0_alpha.ebuild
This isn't used anywhere in the build, so it can be dropped.
> Drop LOCAL_RUST_PATH from the alpha release

- app-emacs/rust-mode/rust-mode-1.0.0_alpha.ebuild
- app-emacs/rust-mode/rust-mode-9999.ebuild
- app-shells/rust-zshcomp/rust-zshcomp-1.0.0_alpha.ebuild
- app-shells/rust-zshcomp/rust-zshcomp-9999.ebuild
- app-vim/rust-mode/rust-mode-1.0.0_alpha.ebuild
- app-vim/rust-mode/rust-mode-9999.ebuild
- dev-lang/rust-bin/rust-bin-999.ebuild
- dev-lang/rust/rust-1.0.0_alpha.ebuild
- dev-lang/rust/rust-999.ebuild
- dev-lang/rust/rust-9999.ebuild
The EAPI value doesn't need to be quoted since it doesn't include
spaces.
> Do not quote the EAPI value

- dev-lang/rust/rust-1.0.0_alpha.ebuild
- dev-lang/rust/rust-999.ebuild
- dev-lang/rust/rust-9999.ebuild
Little addition to 2106e48dfd2acfb2893db54dd0dcbd63d286d3bf which
disable ldconfig for live ebuilds.
> rust-999.ebuild and rust-9999.ebuild ldconfig fix

- dev-lang/rust/rust-9999.ebuild
- dev-rust/cargo/cargo-9999.ebuild
- dev-rust/rust-bindgen/rust-bindgen-9999.ebuild
- dev-util/racer/racer-9999.ebuild
Using https is an improvement to building because at least you can verify that no-one is modifying your git repository in-flight.
This is part of https://github.com/Heather/gentoo-rust/issues/83
> Problem: Some ebuilds were using the insecure git:// url scheme

- dev-lang/rust/rust-1.0.0_alpha.ebuild
- dev-lang/rust/rust-1.0.0_alpha2.ebuild
- dev-lang/rust/rust-999.ebuild
- dev-lang/rust/rust-9999.ebuild
At this time, more dependencies (Pandoc and XeLaTeX) for the flag ware *not* added, so only docs built using rustdoc are installed on any machine. I'll make separated issue to discuss that.
Also, rust-bin hasn't improved yet. Stay tune.
See also: #77
> Add `doc` USE flag to dev-lang/rust.

- dev-rust/cargo/cargo-9999.ebuild
If this libs are missing from system, cargo will statically link to
its own bundled libs. But if they are present, then there is no way
to prevent cargo dynamically linking against them.
> dev-rust/cargo: add dependencies

- dev-lang/rust/rust-999.ebuild
- dev-lang/rust/rust-9999.ebuild
Upstream has removed the --disable-verify-install option from the
configure script and therefore specifying it causes configure to fail
upstream commit: rust-lang/rust@bc9f16c59960cfb306178428956f8446337d27e7
> remove --disable-verify-install configure option

- dev-lang/rust/rust-1.0.0_beta.ebuild
- dev-lang/rust/rust-1.0.0_beta2.ebuild
- dev-lang/rust/rust-999.ebuild
... plus some refactoring.
As @himikof mentioned comment to #95, the main difference is that without this flag unstable features are enabled in beta build.
> Add --release-channel to ./configure options

- README.md
I have added info for users and developers. I hope it is useful.
Note, that eselect part (for developers) describes current git eselect-rust (not yet released) that supports better symlinks management. I will release this a little bit later after appropriate changes of rust ebuilds and testing.
This is the first step to make rust-bin slottable, which makes sense now because of introduced release channels. We also will need to discuss exact slotting policy (I remeber there was such an issue, if no I will create a new one). Better mapping between slots and release channels will be the second step.
> [README] add user's and developer's guides

- dev-lang/rust-bin/rust-bin-1.0.0_beta2.ebuild
- dev-lang/rust-bin/rust-bin-1.0.0_beta3.ebuild
- dev-lang/rust-bin/rust-bin-999.ebuild
dev-lang/rust-bin-1.0.0_beta3 doesn't have docs and cargo, removing USEs
add || die to install script invocation
> [dev-lang/rust-bin] fix ebuilds

- dev-rust/cargo/cargo-9999.ebuild
This is a temporary workaround for the bug in `git2-rs` build script, which is already fixed in the upstream (alexcrichton/git2-rs#63) but will take time to land in cargo.
> Fix cargo build when dev-libs/libgit2 is installed (#124)

- dev-lang/rust/rust-1.0.0.ebuild
When running install, the Rust build system tries to be clever and drop privileges for part of the process by sudoing back to $SUDO_USER, if it is set. Unfortunately, this breaks when the contents of $SUDO_USER (my username) doesn't match the user used to unpack and build the compiler (paludisbuild), resulting in a permission denied error during the install step. The simplest solution is just to unset SUDO_USER.
> Fix build when using sudo and Palidus

- dev-rust/cargo/cargo-0.2.0.ebuild
- dev-rust/cargo/cargo-9999.ebuild
Should fix #129.
Not tested yet, since downloading all needed stuff takes ages. As soon as I'll be able to confirm that it does help, I'll comment.
> [dev-rust/cargo] depend on curl[ssl] rather than curl[curl_ssl_openssl]

- dev-lang/rust-bin/rust-bin-99.ebuild
- dev-lang/rust-bin/rust-bin-999.ebuild
About
>very bad practics to use `grep` in ebuilds
Another way is:
```bash
while IFS='' read -r line || [[ -n "$line" ]]; do
case "$line" in
*std*)
local std="$line"
;;
esac
done < "./components"
```
Also, I grepped through `/usr/portage` and found many ebuilds which use `grep`, including `sudo`, `grub` and `python`
> dev-lang/rust-bin: also include stdlib in beta Rust install

- dev-lang/rust/rust-1.5.0.ebuild
That flag used to exist in dev-lang/rust-1.2.0 and I don't know why it's
been removed. Rust compiles fine on my system with it.
> dev-lang/rust: bring back the system-llvm flag

- dev-lang/rust/rust-1.7.0-r1.ebuild
Without a separate variable for common dependencies, there is no way,
for example, to add a pure runtime dependency.
> dev-lang/rust: create COMMON_DEPEND variable

- dev-lang/rust/rust-1.7.0-r1.ebuild
Technically prior to LLVM 3.7, Gentoo still supports static linking which
is what the Rust build does by default so LLVM is not a run-time depend.
Package-Manager: portage-2.2.26
Manifest-Sign-Key: 0xA2BC03DC87ED1BD4!
Signed-off-by: Doug Goldstein <cardoe@gentoo.org>
> dev-lang/rust: fix llvm dependency

- dev-lang/rust/rust-9999.ebuild
Fixes https://github.com/gentoo/gentoo-rust/issues/186.
> dev-lang/rust: it's called get-stage0 now

- dev-lang/rust/rust-1.9.0.ebuild
LLVM 3.7.0 broke API and ABI compatibility with previous and subsequent
versions, preventing its use with Rust. Version 3.7.1 fixed that
breakage. As such, Rust with USE=system-llvm can now use LLVM from 3.6.0
through at least 3.8.0, with the exception of 3.7.0.
> dev-lang/rust: Fix dependency on sys-devel/llvm post 3.7.0

- dev-util/cargo/cargo-0.9.0.ebuild
- dev-util/cargo/cargo-9999.ebuild
For the latest cargo version in this repo (0.9) and the git build.
Same thing would probably work for older versions, but I figure there's probably not much point to it.
Closes #188
> Add libressl USE flag #188

- dev-lang/rust/rust-1.11.0.ebuild
- dev-lang/rust/rust-1.12.1-r1.ebuild
- dev-lang/rust/rust-99.ebuild
- dev-lang/rust/rust-999.ebuild
- dev-lang/rust/rust-9999.ebuild
This commit adds a `source` use flag to dev-lang/rust ebuilds, which installs the rust source in `/usr/share/${P}/src`. This is useful for other packages such as dev-util/racer, keeping the sources in sync with the installed libs. In support of that, this commit also exports the location of the source install to the environment variable racer looks for.
This was requested in #149.
> Add source use flag for racer completion

- dev-lang/rust/rust-99.ebuild
the following script was renamed.
rustc/src/etc/get-snapshot.py -> rustc/src/etc/get-stage0.py"
> fix dev-lang/rust:beta unpack/fetch script

- dev-lang/rust/rust-99.ebuild
I'm almost sure that my hacks is not a good thing to do, but they allowed me to build dev-lang/rust-99. I'm sending pull-request in hope it helps you to figure out the right way to deal with issues I discovered.
This patch solves two issues. The first one is not matching names of real directory with sources and content of $MY_P. I done it by simple `mv'.
The second issue is missing /usr/lib64/libLLVM*.a files, for example: /usr/lib64/libLLVMSupport.a.
I have found that build script (/var/tmp/portage/dev-lang/rust-99/work/rustc-beta/src/librustc_llvm/build.rs) runs llvm-config with option --link-static, but this doesn't work. At least while combined with USE=system-llvm. Those build.rs checks for LLVM_LINK_SHARED environment variable (at least for some versions of llvm), and exporting it …
> Fixes for workdir and to allow build with shared libraries of system-llvm

- dev-lang/rust/rust-999.ebuild
- dev-lang/rust/rust-9999.ebuild
Upstream has dropped support for the old Makefile build system for the newer rustbuild build system. This commit changes the ebuilds of the `git` and `nightly` slots to make use of it.
This also adds the `+system-llvm` use flag to both ebuilds that the official dev-lang/rust package permits. It currently does nothing due to an issue with `llvm-config`, but I'll be looking into that.
Finally, this makes both rust-999.ebuild and rust-9999.ebuild identical in content. I figure nightlies and the direct git upstream should not differ in the build process at all, so we can just check the slot we're installing for and change a few variables to differ between them.
> Use the new rustbuild build system

- dev-lang/rust-bin/metadata.xml
- dev-lang/rust-bin/rust-bin-999.ebuild
this files are used by [Rust Language Server](https://github.com/rust-lang-nursery/rls#download-the-libs)
> dev-lang/rust-bin:nightly: install stdlib analysis files

- dev-lang/rust/rust-999.ebuild
- dev-lang/rust/rust-9999.ebuild
This installs rust-lldb to rust-lldb-999 or rust-lldb-9999 depending on the slot you install. This allows eselect to determine which one to use.
This fixes #227
> Move lldb to individual versions

- dev-lang/rust/metadata.xml
- dev-lang/rust/rust-9999.ebuild
1. Removes --disable-rustbuild: https://github.com/rust-lang/rust/pull/39774
2. Add support for sanitizers: https://github.com/rust-lang/rust/pull/38699
> Add support for sanitizers. Remove rustbuild option.

- dev-lang/rust/rust-999.ebuild
Remove `--disable-rustbuild` because it's the only build system now; add `emake dist`, just like in 9999 ebuild
Closes #235
> Fix nightly ebuild

- dev-lang/rust/files/rust-9999-enable-analysis-dev.patch
- dev-lang/rust/metadata.xml
- dev-lang/rust/rust-9999.ebuild
Analysis files installs into directory which used in: https://github.com/nrc/rls-analysis/blob/master/src/lib.rs#L113
> dev-lang/rust-9999: build and install stdlib analysis files.

- dev-lang/rust/rust-1.12.1-r1.ebuild
- dev-lang/rust/rust-1.13.0.ebuild
- dev-lang/rust/rust-1.14.0-r1.ebuild
- dev-lang/rust/rust-1.14.0.ebuild
- dev-lang/rust/rust-99.ebuild
- dev-lang/rust/rust-999.ebuild
- dev-lang/rust/rust-9999.ebuild
We need to ask `llvm-config` to link to dynamic libraries (it tries to find static libraries by default) because LLVM ebuild does not provide an option to compile static libraries, this PR finally allows to use the `system-llvm` flag.
> Link to llvm dynamically when using system-llvm

- dev-util/cargo-bin/cargo-bin-99.ebuild
- dev-util/cargo-bin/cargo-bin-999.ebuild
Fix changing directory name: `bash_completion.d` to `bash_completions.d`.
> dev-util/cargo-bin: Fix bash_completion installation

- dev-lang/rust/metadata.xml
- dev-lang/rust/rust-9999.ebuild
Fix configuration after merging PR https://github.com/rust-lang/rust/pull/40584
Remove `analysis` flag and use `tools` as it manages other tools too.
> dev-lang/rust: Fix configuration after removing --enable-save-analysis flag.

- dev-lang/rust/rust-9999.ebuild
Therefore the root is now there and `llvm-config --obj-root` knows about it
> LLVM 4+ now has it's own dir at /usr/lib/llvm/N

- dev-lang/rust/rust-1.18.0.ebuild
When emerging =dev-lang/rust-1.18.0[doc], the merge fails on l.152 of the ebuild: the source path is not found.
Indeed all doc files are already in _"${D}/usr/share/doc/rust-1.18.0/"_, and do not need to be moved.
> Remove doc path fixup for rust-1.18.0.ebuild

- dev-lang/rust/rust-9999.ebuild
Fix #255 . It's just deletes `cargo` file after installation.
May be it better to have `virtual/cargo` to allow `cargo` from `dev-lang/rust[tools]` or disable some step to avoid `cargo` installation.
> dev-lang/rust-9999: Remove cargo if build with tools enabled.

- dev-rust/rust-bindgen/rust-bindgen-9999.ebuild
The GitHub repository in the ebuild is no longer available and was replaced by the current one.
> dev-rust/rust-bindgen is broken due to non existing repository

- dev-lang/rust/rust-9999-r1.ebuild
Move to prefered `x.py` build system.
Fix https://github.com/gentoo/gentoo-rust/issues/277 with enabling rpath (After https://github.com/rust-lang/rust/issues/43289 will be fixed it would be possible to disable back.)
All use flags should works same but I remove `libcxx` flag as I don't find in `config.toml` options for it.
Based on examles from https://bugs.gentoo.org/show_bug.cgi?id=617744
> dev-lang/rust: Rewrite live-ebuild to use x.py.

- dev-lang/rust/rust-1.19.0-r2.ebuild
Hi,
This PR installs an individual version of rust-lldb instead of just installing the non individual /usr/bin/rust-lldb.
> dev-lang/rust : installs rust-lldb with the right name

- dev-lang/rust/rust-9999-r1.ebuild
https://github.com/rust-lang/rust/pull/43694 fixed error when building rustdoc without rpath. Now it possible to disable rpath.
> Disable rpath after https://github.com/rust-lang/rust/pull/43694

- dev-lang/rust/rust-9999-r1.ebuild
Fixes #287.
Fix git commit hash and date in a verbose version.
> Fix #287 and restore git data.

- dev-util/cargo-bin/cargo-bin-99.ebuild
- dev-util/cargo-bin/cargo-bin-999.ebuild
Rust has changed the bash completion dir in
https://github.com/rust-lang/rust/commit/dda2d756facc1c8100261e2ebd4e115c84f515cc
> dev-util/cargo-bin: Fix bash_completion dir

- dev-lang/rust-bin/rust-bin-99.ebuild
- dev-lang/rust-bin/rust-bin-999.ebuild
- dev-util/cargo-bin/cargo-bin-99.ebuild
- dev-util/cargo-bin/cargo-bin-999.ebuild
- dev-util/cargo/cargo-9999.ebuild
These beta and nightly versions are downloaded with wget and they do not have any checksum checks. Better use https.
> Use https when downloading sources.

- dev-util/cargo/cargo-9999.ebuild
`cargo` binary was downloaded, but wasn't used, so build worked only if `cargo` was already installed
> dev-util/cargo-9999: fix build

- dev-lang/rust/rust-1.22.1.ebuild
- dev-lang/rust/rust-1.23.0.ebuild
- dev-lang/rust/rust-9999-r1.ebuild
The only part of the MAKEOPTS variable that x.py understands is "-j \<number>" or "--jobs \<number>". Something like "-j9 -l9" would break the build, so we extract just what we support from the global variable.
> dev-lang/rust - proper MAKEOPTS handling

- dev-util/cargo/cargo-0.23.0.ebuild
\>=dev-lang/rust-1.22.1 cannot be installed at the same time as <=dev-util/cargo-0.22.0
and packages like sys-apps/ripgrep and www-client/firefox have a hard
dependency on dev-util/cargo.
This ugly hack solves the problem of using recent rust versions from the
"rust" overlay at the same time with firefox and/or ripgrep from the
main repo.
This virtual package should be removed in a few years, when Gentoo
developers solve the problem properly by changing the dependencies of
those two packages.
> dev-util/cargo-0.23.0 - virtual package to fix issue #308

- dev-lang/rust/rust-9999.ebuild
- dev-util/cargo/cargo-9999.ebuild
Remove cargo and rustfmt from rust installation.
Restore original cargo installation.
Change USE flag `tools` to `extended`.
> Remove cargo and rustfmt from rust installation.

- virtual/rust/rust-9999.ebuild
cargo-9999 depends on >=virtual/rust-999 but there's no >=virtual/rust-999
> Add virtual/rust-9999 to satisfy cargo-9999 dependency

- dev-lang/rust/rust-9999.ebuild
usex expects 2 arguments and if the second argument is not
given it defaults to "no" causing build to fail when "extended" use-flag
is enabled.
> rust-9999.ebuild: fix usage of usex

- dev-lang/rust/metadata.xml
libcxx is now imported with clang flag
> [dev-lang/rust] remove unused flag libcxx

- dev-lang/rust/metadata.xml
Fix #328 
I think that is better to uniform this use flag also with rust-bin. Doubs?
> add extended use metadata description

- dev-util/clippy/clippy-9999.ebuild
Fixes error: `error: To build the current package use `cargo build`, to install the current package run `cargo install --path .`, otherwise specify a crate to install from crates.io, or use --path or --git to specify alternate source`
> Fix clippy compilation.

- dev-vcs/pijul/pijul-0.10.0.ebuild
The thrussh-libsodium crate depends on libsodium. Make sure that
dev-libs/libsodium is a dependency of this ebuild.
> Add dev-libs/libsodium to pijul DEPEND

- .travis.yml
- dev-lang/rust-bin/rust-bin-9999.ebuild
Also added "infrastructure" for adding other [platforms](https://forge.rust-lang.org/platform-support.html).
Put `USE_EXPAND="RUSTLIB_TARGETS"` into your `make.conf` to make it look a little nicer.
CC #356.
> Add webassembly to rust-bin

- dev-lang/rust/metadata.xml
- dev-lang/rust/rust-9999.ebuild
Enables wams32-unknown-unknown target.
Enables installation LLD linker.
Works only with `RUSTFLAGS="-C linker=lld"`. I'm not sure how to fix it.
> Add support for WebAssembly

- dev-lang/rust/metadata.xml
- dev-lang/rust/rust-9999.ebuild
Removes `extended` flag. Uses separate flags for tools. Adds flag `clippy`.
> Split extended flags same way as gentoo version

- eclass/cargo.eclass
> cargo.eclass: depend on virtual/cargo instead of dev-util/cargo

- dev-lang/rust/files/rust-9999-fix-clippy-sysroot.patch
- dev-lang/rust/rust-9999.ebuild
Fix #368. Patch will be removed after https://github.com/rust-lang-nursery/rust-clippy/pull/3257 landed.
Use multiprocess eclass.
RLS requires analysis and sources.
Fix behavior if EPYTHON not found.
> Updates for =dev-lang/rust-9999

- dev-lang/rust/rust-9999.ebuild
After https://github.com/rust-lang/rust/pull/55238 jemalloc is managed with `rust.jemalloc` option.
> Use new rust.jemalloc option

- dev-lang/rust/files/rust-9999-fix-codegen-path.patch
- dev-lang/rust/files/rust-9999-fix-rustdoc.patch
- dev-lang/rust/rust-9999.ebuild
Reverts https://github.com/rust-lang/rust/issues/58587 to build rustdoc.
Fix codegen search and clippy.
> dev-lang/rust-9999: latest fixes

- dev-lang/rust/rust-9999.ebuild
Fixes #402. `debuginfo = false` hasn't been valid since Rust commit [`28405ca`](https://github.com/rust-lang/rust/commit/28405cabd50181afa6eccfd7f2ee8eb363d35594); it's no longer a boolean. For rust-9999 to build, it should be replaced with `debuginfo-level = 0` or `debuginfo-level = 2` depending on the setting of the `debug` USE flag.
> dev-lang/rust: set debuginfo-level instead of boolean in config.toml

- dev-lang/rust/rust-9999.ebuild
Fixes #375. Rust's `bootstrap.py` [vendors dependencies when `SUDO_USER` is set](https://github.com/rust-lang/rust/blob/f693d339f175b3aa23a91c62632c5f0c86886059/src/bootstrap/bootstrap.py#L779-L786), which flat out doesn't work in the ebuild's environment (especially with `FEATURES="network-sandbox"` enabled), so if emerge is invoked with `sudo`, the build breaks.
Fortunately this bug only impacted `dev-lang/rust-9999`.
This is much more elegant than using `package.env` or [a patch](https://github.com/gentoo/gentoo-rust/issues/375#issuecomment-504210488), and it really ought to work by default anyway.
> dev-lang/rust: unset SUDO_USER to disable vendoring

- dev-lang/rust/rust-1.37.0-r666.ebuild
Since this package is compartible with openssl-1.1.1, it should accept any letter release (currently openssl-1.1.1b-r2 and openssl-1.1.1c are in the tree) as the correct dependency.
> Accept letter releases of dev-libs/openssl-1.1.1

- dev-lang/rust-bin/rust-bin-9999.ebuild
This is @temporary-username-largedicks's patch from #421
> Fix rust-bin-9999 ebuild: Do not fetch bogus url

- dev-lang/rust/rust-9999.ebuild
@o01eg @cnd asking for a review: 
should we follow upstreams choice of llvm-9? 
Also: does my code do that? I'm not absolutly sure :-)
> dev-lang/rust-9999: raise llvm slot to 9 

- dev-lang/rust-bin/rust-bin-999.ebuild
this allows testing for beta, if desired 
the build is a copy of the rust-bin-9999 ebuild, with nightly replaced by beta, that's it :-)
> dev-lang/rust-bin: add live ebuild for beta channel

- dev-rust/cranelift-tools/cranelift-tools-0.45.0.ebuild
this will only show on cmake and gcc free systems
> cranelift-tools: wabt-sys demands cmake and gcc

- dev-lang/rust/rust-9999.ebuild
this is more closer to the instructions given in the comments of the ebuild.
> dev-lang/rust: allow llvm 8 or 9 for the live ebuild with system-llvm

- dev-lang/rust/rust-999.ebuild
- dev-lang/rust/rust-9999.ebuild
the xz-utils dependency is not needed, as the whole bootstrap script is done via the python-lzma module
> dev-lang/rust: the bootstrap script is executed via python, not via /usr/bin/xz
